### ISSUE TITLE
License files missing

### ISSUE THREAD

**Issue by RAnders00** [murarth/smallstr#11]
Readme says: "See LICENSE-APACHE and LICENSE-MIT for details." - The files are missing however. I can create a PR if needed.

Also, the Cargo.toml license entry should probably be `(MIT OR Apache-2.0)` instead of the current `MIT/Apache-2.0`, so it becomes a valid SPDX license expression as documented: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by murarth** [comment]
Thank you for bringing this to my attention. I've just pushed a commit to fix these issues.
