### ISSUE TITLE
Conversion to Box<str>

### ISSUE THREAD

**Issue by CryZe** [murarth/smallstr#5]
It seems like at the moment there's no way to convert to `Box<str>` without always allocating. This should be a trivial addition and would speed up my code a bit.

**Comment by murarth** [comment]
You can use `small_str.into_string().into_boxed_str()`, which will allocate only if the contents are not yet spilled (and reallocate, if necessary, to shrink the capacity to be equal to length).

I can add a convenience method `into_boxed_str`, as a counterpart to `SmallVec::into_boxed_slice`, but it would be implemented exactly as my above suggestion. ([This is how](https://docs.rs/smallvec/1.2.0/src/smallvec/lib.rs.html#901-903) `SmallVec::into_boxed_slice` is implemented, as well.)
