### ISSUE TITLE
The serde feature should not add an std dependency

### ISSUE THREAD

**Issue by sffc** [murarth/smallstr#6]
Serde supports no_std, but it is enabled by default in the `std` feature.  So, using the `serde` feature of `smallstr` pulls in `std`, which breaks a `no_std` build.  I think you can fix this by adding `default-features = false` on the `serde` dependency in Cargo.toml.  Also consider bubbling up an `std` feature back into `serde`.

**Comment by murarth** [comment]
I've submitted PR #7 to address this issue.
Please let me know if this solves your issue or if I've left anything out.
