### ISSUE TITLE
Serde and no_std

### ISSUE THREAD

**Issue by sffc** [murarth/smallstr#8]
One more thing:

I added a `smallstr` dependency to my no_std project as so:

```
[dependencies.smallstr]
version = "0.2.0"
default-features = false
features = ["serde"]
git = "https://github.com/murarth/smallstr"
```

It gets further than it did before #7, but now it gets stuck on:

```
error[E0407]: method `visit_string` is not a member of trait `Visitor`
   --> /home/sffc/.cargo/git/checkouts/smallstr-93667b6dc37af95b/68efc08/src/string.rs:529:5
    |
529 | /     fn visit_string<E: Error>(self, v: String) -> Result<Self::Value, E> {
530 | |         Ok(v.into())
531 | |     }
    | |_____^ not a member of trait `Visitor`

error: aborting due to previous error
```

Here's the definition in Serde:

https://docs.serde.rs/src/serde/de/mod.rs.html#1508

```
    #[inline]
    #[cfg(any(feature = "std", feature = "alloc"))]
    fn visit_string<E>(self, v: String) -> Result<Self::Value, E>
    where
        E: Error,
    {
        self.visit_str(&v)
    }
```

Should you give the `alloc` feature to `serde`, since I think [SmallVec already uses `alloc`](https://github.com/servo/rust-smallvec/blob/master/lib.rs#L82) in `no_std`?

**Comment by murarth** [comment]
I've just pushed a commit that should resolve this issue.

This should have been caught in testing, but it seems that Cargo is not honoring `default-features = false` when building from the `smallstr` project. It seems related to this issue: rust-lang/cargo#8366

**Comment by sffc** [comment]
Thank you!  Confirmed that smallstr works now when installed from c28b7514ce047c24ad181197bf0c55321edd05df in both `std` and `no_std` with the `serde` dependency. :+1:

**Comment by appetrosyan** [comment]
Now that `0.3.0` is available, the latest upstream also works with `serde` and `no_std`.
